services:
  web:
    build: .
    container_name: mychat_web
    command: daphne -b 0.0.0.0 -p 8000 mychat.asgi:application
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=mychat.settings
      - DEBUG=True
    # Réseau pour la communication interne
    networks:
      - mychat_network

  nginx:
    image: nginx:alpine
    container_name: mychat_nginx
    ports:
      - "80:80"  # Nginx écoute sur le port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/static
    depends_on:
      - web
    networks:
      - mychat_network

  redis:
    image: redis:7
    container_name: mychat_redis
    ports:
      - "6379:6379"
    networks:
      - mychat_network

  tailwind:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: >
      npx tailwindcss -i ./static/src/input.css -o ./static/src/output.css --watch
    networks:
      - mychat_network

# Réseau personnalisé
networks:
  mychat_network:
    driver: bridge
