# Generated by Django 5.2.5 on 2025-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_auth_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
