# Generated by Django 5.2.6 on 2025-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_face_auth_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="face_image_registered",
            field=models.BooleanField(default=False),
        ),
    ]
